apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: ingress-website
spec:
  rules:
  - host: explorecalifornia.com
    http:
      paths:
      - backend:
          service:
            name: {{ .Values.serviceName }}
            port:
              number: {{ .Values.sourcePort }}
        path: /
        pathType: Prefix